services:
  - name: my-type-is-the-bag
    type: web
    env: node
    repo: https://github.com/FrogiesArcade/FrogiesArcade-v3-Portable
    region: oregon
    plan: free
    
    buildCommand: "npm install"
    startCommand: "node index.js"
